
AntiCheat_CONVAR_REPLICATED = 1
AntiCheat_CONVAR_STATIC = 2
AntiCheat_CONCOMMAND_EXIST = 3
AntiCheat_CONVAR_EXIST = 3

AntiCheat_LOG = 1
AntiCheat_KICK = 2
AntiCheat_BAN = 3



local AntiCheat_Convars = { 
        "bs_force_load",
        "lua_logo_reload",
        "lua_run_quick",
        "bs_reload",
        "bs_unload",
        "bs_inject",
        "+bs_getview",
        "+bs_getpos",
        "odius_menu",
        "+odius_aim",
        "+odius_pkmode",
        "fl_fillhp",
        "server_command",
        "toggle_target",
        "target_menu",
        "+aim",
        "anthrax_banadmins",
        "anthrax_demoteadmins",
        "lol_rcon",
        "+follow_aim",
        "cs_lua",
        "anthrax_filemenu",
        "+anthrax_floodserver",
        "getrcon",
        "exploit_admin",
        "exploit_bans",
        "exploit_cfg",
        "exploit_rcon",
        "lix_lesp_rotate1",
        "lix_lesp_rotate2",
        "lix_lesp_rotate3",
        "lix_lesp_rotate",
        "sv_add1",
        "sv_run1",
        "exploit",
        "print_server_cfg",
        "print_file",
        "dump_remote_lua2",
        "print_file_listing_load",
        "sv_printdirfiles",
        "sv_printdir",
        "****_admins",
        "aah_setupspeedhack",
        "_timescale",
        "+enabled",
        "+triggerbot",
        "inc_g",
        "Smelly_Print_IPs",
        "Smelly_Clear_IPs",
        "+autofire",
        "spinlol",
        "pp_pixelrender",
        "startspam",
        "stopspam",
        "+makesound",
        "makesound",
        "+pk",
        "ThrowMagneto",
        "kon_chatspam",
        "kon_stopspam",
        "RLua",
        "Orgflashstyle1",
        "Orgflashstyle2",
        "se_add",
        "mh_unlock",
        "mh_toggleflag",
        "mh_keypad",
        "mh_open",
        "mh_turn180",
        "mh_esp_rehook",
        "mh_owners",
        "+qq_aimbot_enabled",
        "qq_menu",
        "+qq_nospread_triggerbot",
        "+qq_speedhack_speed",
        "go_unconnected",
        "+nou",
        "metalslave_aimbot_reload",
        "metalslave_aimbot_toggle",
        "metalslave_aimbot_menu",
        "metalslave_chams_reload",
        "cf_aim_toggle",
        "+cf_bunnyhop",
        "CrashTheServer",
        "UltraCrashTheServer",
        "+cal_menu",
        "+cal_aim",
        "Isis_Menu_Reload",
        "+Isis_Menu",
        "+kilos_aim",
        "Isis_InteractC4",
        "+Isis_Aim",
        "Isis_Spin",
        "+Isis_Speed",
        "cf_freeze",
        "cf_menu",
        "+cf_aim",
        "cf_menu_toggle",
        "+cf_speed",
        "+DragonBot_Aim",
        "DragonBot_menu",
        "sh_luarun",
        "2a1f3e4r5678j9r9w8j7d54k6r2a84",
        "falco_runlooah",
        "falco_openlooah",
        "falco_rotate1",
        "falco_rotate2",
        "frotate",
        "+falco_makesound",
        "falco_makesound",
        "+hermes_aim",
        "_PoKi_menu_reload",
        "spamjeeps",
        "spamchair",
        "falco_hotkey",
        "falco_hotkeyList",
        "+cb_aim",
        "vlua_run",
        "sh_print_traitors",
        "+sh_triggerbot",
        "sh_runscripts",
        "sh_togglemenu",
        "gen_aim",
        "gen_autoshoot",
        "gen_speed",
        "+gen_bhop",
        "+gen_aim",
        "+gen_speed",
        "Ares_ForceImpulse",
        "Ares_Menu_ESP",
        "Ares_Menu_Misc",
        "Ares_Menu_AimBot",
        "+Ares_Pointer",
        "+Ares_SlowNikes",
        "+Ares_Aim",
        "+Ares_Nikes",
        "+Ares_PropKill",
        "Ares_Print_IPs",
        "Ares_Clear_IPs",
        "+MAim",
        "ms_pato",
        "+MSpeed",
        "ms_sv_cheats",
        "+MPause",
        "+zumg",
        "_fap_reload_menu",
        "ThermHack_ToggleMenu",
        "cub_toggle",
        "hera_convar_get",
        "hera_convar_set",
        "hera_include",
        "hera_runstring",
        "Monster_Menu",
        "x_reload",
        "x_menu",
        "+fox_aim",
        "+hax_rapidfire",
        "+Hax_aimbot",
        "+Hax_Menu",
        "+Hax_Zoom",
        "+hera_speed",
        "+TB_Bhop",
        "TB_Console",
        "+ATMenu",
        "+AimAssist",
        "+AimBHOP",
        "ReloadAA",
        "h_runscript",
        "h_openscript",
        "h_firewall",
        "h_gtower_debug",
        "h_bo_thirdperson",
        "h_helxa_encrypt",
        "h_helxa_decrypt",
        "bypass_se",
        "+hax_admin",
        "Neon_LoadMenu",
        "+Neon_Aim",
        "+Neon_SpeedHack",
        "+Neon_PropKill",
        "Neon_SayTraitors",
        "Neon_ForceCheats",
        "+neon_menu",
        "sb_toggle",
        "sh_menu",
        "sh_togglemenu",
        "+sh_triggerbot",
        "sh_print_traitors",
        "+sykranos_is_sexy",
        "+sykranos_is_really_sexy",
        "+sh_bhop",
        "+li_bhop",
        "SE_ByPass",
        "se_on",
        "+Aim",
        "SpamTime",
        "SethHack_panic",
        "SethHack_lua_run",
        "SethHack_lua_openscript",
        "+SethHackToggle",
        "+SethHack_Menu",
        "deathrun_qq",
        "+SethHack_Speed",
        "SethHack_ff_toggle",
        "SethHack_wallhack_wire",
        "SethHack_wallhack_player",
        "SethHack_Clear_All",
        "SethHackToggle",
        "SethHack_triggerbot_toggle",
        "SethHack_AddNPCfriend",
        "SpamMenu",
        "Inkbot_Crack",
        "Ink_LoadMenu",
        "+Propkill",
        "+Ink_Aim",
        "Ink_menu",
        "ihpublicaimbot_reload",
        "ihpublicaimbot_toggle",
        "+ihaimbot",
        "ihpublicaimbot_menu",
        "lagon",
        "lagoff",
        "fap_aimbot_toggle",
        "+Nis_Menu",
        "+sh_bhop",
        "pb_aim_trigger",
        "pb_load",
        "+TB_Aim",
        "+TB_Menu",
        "+TB_RapidFire",
        "+TB_Speed",
        "Spam_Props-V2",
        "Spam_Chat-v2",
        "pb_menu",
        "+bc_aimbot",
        "-bc_aimbot",
        "+bc_spamprops",
        "bc_ips",
        "+bc_speedshoot",
        "bc_reload",
        "bc_unload",
        "wots_attack",
        "_fap_reload",
        "SE_AddFile",
        "SE_RemoveFile",
        "SE_LoadScripts",
        "+pb_aim",
        "pb_menu",
        "Spam_Props",
        "Spam_Chat",
        "+li_aim",
        "+li_menu",
        "li_menu",
        "+sh_menu",
        "+Mawpos",
        "gzfaimbot_reload",
        "gzfaimbot_toggle",
        "gzfaimbot_enabled",
        "asb_base_reload",
        "asb_base_unload",
        "+shenbot_aimbot",
        "shenbot_menu",
        "shenbot_bunnyhoptoggle",
        "-shenbot_aimbot",
        "SpinBot_on",
        "aimbot_off",
        "_aimbot",
        "lua_dofile_cl",
        "lua_dostring_cl",
        "ph0ne_aim",
        "ph0ne_aimcancel",
        "ph0ne_autoshoot",
        "+trooper_menu",
        "BMpublicaimbot_reload",
        "BMpublicaimbot_toggle",
        "+BMaimbot",
        "BMpublicaimbot_menu",
        "spamchat",
        "_fap_menu_reload",
        "rs",
        "sh_triggerbot",
        "sh_showips",
        "+sh_speed",
        "+sh_aim",
        "sh_toggleaim",
        "helix_chatspammer",
        "helix_undo",
        "helix_propspam",
        "helix_admins",
        "helix_rpnamespammer",
        "+helix_speed",
        "helix_crypto_binary",
        "helix_forcerandomname_on",
        "helix_forcerandomname_off",
        "helix_troll",
        "+helix_aim",
        "helix_cvarmenu",
        "formatlaser",
        "+Helix_Menu",
        "helix_reload",
        "helix_propspammer2",
        "helix_barrelbomb",
        "helix_unload",
        "helix_speed",
        "helix_blocklua",
        "helix_propspam_mdl",
        "helix_aim_bone",
        "helix_aim_crosshair",
        "helix_aim_fov",
        "helix_aim_los",
        "helix_aim_norecoil",
        "helix_aim_players",
        "helix_aim_shoot",
        "helix_aim_team",
        "helix_aim_trigger",
        "h_name",
        "+bb_menu",
        "bb",
        "ForceLaunch_BB",
        "jonsuite_unblockx",
        "bacon_lua_openscript",
        "+fox_aim",
        "discord1",
        "discord2",
        "hera_runstring",
        "aa_toggle",
        "Bacon_TriggerBotDelay",
        "Bacon_load",
        "bacon_chatspam",
        "bacon_namechange",
        "bacon_chatspam_interval",
        "bacon_norecoil",
        "Bacon_AntiSnap",
        "bacon_autoreload",
        "+hermes_menu",
        "+sykranos_is_sexier_then_hex",
        "sykranos_is_sexy_menu",
        "+hermes_speed",
        "AGT_AutoshootToggle",
        "AGT_AimBotToggle",
        "AGT_RandomName",
        "nbot_aimfixer",
        "nbot_speedoffset",
        "nbot_UseSelectedPerson",
        "nbot_autoshoot",
        "fap_enablekeybinding",
        "fap_bind",
        "fap_unbind",
        "lua_se2_load",
        "ah_cheats",
        "ah_changer",
        "ah_speed",
        "ah_aimbot_friends",
        "ah_aimbot",
        "ah_hooks",
        "ah_hookhide",
        "ah_name",
        "ah_antihook",
        "ah_reload",
        "ah_timestop",
        "setconvar",
        "fap_menu",
        "fap_checkforupdates",
        "fap_aim",
        "+fap_aim",
        "fap_aim_toggle",
        "lua_openscript_cl2",
        "raidbot_predictcheck",
        "aa_enabled",
        "BMaimbot",
        "+BMaimbot",
        "aimbot_headshots_on",
        "CBon_Reload_Script",
        "+CBon_menu",
        "ah_chatspammer",
        "ah_spammer",
        "ah_reload",
        "+ah_menu",
        "+nbot_options",
        "sm_fexec",
        "GAT_RandomName",
        "name_menu",
        "namechanger_on",
        "cl_name",
        "+wots_toggleimmunity",
        "send_file",
        "Bacon_Reload_Script",
        "fap_reload",
        "download_file",
        "upload_file",
        "plugin_load",
        "sethhack_load",
        "st_jumpspam",
        "force_cvar",
        "cl_docrash",
        "_fap_initshit",
        "SE_AddFile",
        "SE_RemoveFile",
        "SE_LoadScripts",
        "+namechanger",
        "RandomNCOn",
        "BlankNCON",
        "PsaySpamOn",
        "GayOn",
        "RatingSpammerOn",
        "+jbf_scan",
        "kennykill",
        "kenny_team",
        "kenny_bodyshots",
        "+kenny",
        "kenny_tagasshole",
        "kenny_addhit",
        "Kenny_noclip",
        "bacon_toggle",
        "Bacon_EntTriggerBot",
        "Bacon_Reload_Script",
        "+wots_spinhack",
        "wots_spinhack",
        "wire_button_model",
        "lol_togglestick",
        "lol_name",
        "lol_copy",
        "lol_****this",
        "lol_barrel",
        "lol_setchat",
        "lol_chat",
        "lol_help",
        "lol_admins",
        "lol_adminalert",
        "lol_cancel",
        "lol_aim",
        "lol_headshot",
        "lol_teamshot",
        "wots_namecracker_menu",
        "wots_namecracker_on",
        "wots_namecracker_off",
        "wots_crash",
        "wots_lag_on",
        "wots_lag_off",
        "speedhack_speed",
        "SetCV",
        "+wowspeed",
        "+gofast",
        "+goslow",
        "JBF_off",
        "JBF_on",
        "JBF_headshots_off",
        "JBF_headshots_on",
        "JBF_enemysonly_on",
        "JBF_enemysonly_off",
        "JBF_playersonly_on",
        "JBF_playersonly_off",
        "_JBF_lagcompensation",
        "JBF_lagcompensation",
        "JBF_suicidehealth",
        "JBF_offset",
        "+BUTT****",
        "entx_spazon",
        "entx_spazoff",
        "entx_setvalue",
        "+butt****",
        "fap_aim_enabled",
        "fap_aim_friendlyfire",
        "fap_aim_targetnpcs",
        "fap_aim_autofire",
        "fap_aim_autoreload",
        "fap_aim_bonemode",
        "fap_aim_targetfriends",
        "fap_aim_targetsteamfriends",
        "fap_aim_targetmode",
        "fap_aim_nospread",
        "fap_aim_maxdistance",
        "fap_aim_targetadmins",
        "fap_aim_antisnap",
        "fap_aim_norecoil",
        "fap_aim_antisnapspeed",
        "******on",
        "******ff",
        "******ff",
        "******fl",
        "******sz",
        "******npc",
        "******w",
        "******i",
        "******shd",
        "******mxsh",
        "******shit",
        "******sd",
        "NameGenDerma",
        "+elebot",
        "+leetbot",
        "elebot_offset",
        "leetbot_offset",
        "elebot_minview",
        "leetbot_minview",
        "elebot_maxview",
        "leetbot_maxview",
        "elebot_boxsize",
        "leetbot_boxsize",
        "elebot_simplecolors",
        "leetbot_simplecolors",
        "elebot_targetteam",
        "leetbot_targetteam",
        "elebot_showadmin",
        "leetbot_showadmin",
        "elebot_filledbox",
        "leetbot_filledbox",
        "wots_attack",
        "+wots_menu",
        "wots_menu",
        "wots_megaspam",
        "wots_namegen_on",
        "wots_namegen_off",
        "name_change",
        "change_name",
        "name_changer",
        "+name_changer",
        "+Bacon_Menu",
        "+BaconToggle",
        "BaconToggle",
        "Bacon_triggerbot_toggle",
        "+Bacon_triggerbot_toggle",
        "Bacon_FF_Toggle",
        "aimbot_scan",
        "+aimbot_scan",
        "+aimbot",
        "aimbot",
        "entx_spazon",
        "entx_spazoff",
        "_aimbot",
        "_aimbot_headshots",
        "aimbot_offset",
        "entx_run1",
        "entx_run2",
        "entx_run3",
        "entx_run4",
        "entx_traceget",
        "entx_camenable",
        "+slobpos",
        "Bacon_Trigger_Bot",
        "+Bacon_Trigger_Bot",
        "Bacon_Ignore_SteamFriends",
        "Bacon_Mode",
        "gzfaimbot_reload",
        "gzfaimbot_toggle",
        "+gzfaimbot",
        "gzfaimbot",
        "gzfaimbot_menu",
        "at_autoaim_on",
        "at_autoaim_off",
        "at_changer_on",
        "at_changer_off",
        "at_norecoil_on",
        "at_norecoil_off",
        "at_menu",
        "at_autoshoot_on",
        "at_autoshoot_off",
        "aa_reload",
        "aa_toggle",
        "+aa",
        "aa_menu",
        "+Mawpos",
        "+nBot",
        "+nbot_Options",
        "nbot_Options",
        "aimbot_on",
        "aimbot_hitbox",
        "aimbot_target_teamates",
        "aimbot_target_closest",
        "aimbot_target_clear",
        "+asb_bot",
        "asb_bot",
        "asb_options",
        "+asb",
        "asb",
        "asb_unload",
        "asb_reload",
        "asb_shoot",
        "+entinfo",
        "entinfo_target",
        "asb_shoot",
        "asb_nospread",
        "asb_players",
        "entinfo_targetplayer",
        "+Sethhacks_Aim",
        "+Sethhacks_Speed",
        "+Sethhacks_Menu",
        "+hera_aim",
        "+hera_speed",
        "+hera_menu",
        "+ubot_viser",
        "-ubot_viser",
        "+save_replay" 
}

function AntiCheat_AddConvar( Name, flType, flResults, iDefault)
	local a = {}
	a.name = Name
	a.type = flType
	a.action = flResults
	if iDefault and flType == AntiCheat_CONVAR_STATIC then
		a.default = iDefault
	end
	table.insert(AntiCheat_Convars, a)
end


function FindPlayerByNetChannel( netchan )
	local adr = netchan:GetAddress():ToString()

	for k, v in pairs( player.GetAll() ) do
		if ( adr == v:IPAddress() ) then
			return v
		end
	end
end

local cvcheck_nr = 1
timer.Create("AntiCheat.CvarCheck", 0.5, 0, function()
	
	if !player.GetAll()[cvcheck_nr] then 
		cvcheck_nr = 1 
		return 
	end
	
	ply = player.GetAll()[cvcheck_nr]
	
	if ply:IsSuperAdmin() then cvcheck_nr = cvcheck_nr + 1 return end
	if ply:IsBot() then cvcheck_nr = cvcheck_nr + 1 return end
	
	cvcheck_nr = cvcheck_nr + 1
end)

local function HandleFail(ply, cvcheck, val)
	if ply:IsSuperAdmin() then return end
	
	local text = ""
	if (cvcheck.type == AntiCheat_CONVAR_REPLICATED) or (cvcheck.type == AntiCheat_CONVAR_STATIC) then
		text = "had " .. cvcheck.name .. " with value: " .. tostring(val)
	else
		text = "had concommand/convar " .. cvcheck.name .. "(status = " .. tostring(val) .. ")"
	end
	
	filex.Append("AntiCheat/" .. string.gsub(ply:SteamID(), ":", "_") .. ".txt", ply:Name() .. " - [" .. ply:SteamID() .. "][" .. ply:IPAddress() .. "] " .. text .. ". On Gamemode: " .. GAMEMODE.Name .. " At: " .. os.date() .. "\n")

	
	for i, v in pairs(player.GetAll()) do
		if v:IsAdmin() then
			v:PrintMessage(HUD_PRINTTALK, "AntiCheat: " .. ply:Name() .. " " .. text)
		end
	end
	
	if (cvcheck.action == AntiCheat_LOG) then return end
	if (cvcheck.action == AntiCheat_KICK) then
		ply:Kick(text)
		return
	end
	--[[if (cvcheck.action == AntiCheat_BAN) or tobool(GetConVarString("AntiCheat_AlwaysBan")) then
		if ULib and ULib.kickban then
			ULib:kickban( ply, tonumber(GetConVarString("AntiCheat_bantime")), "AntiCheat: " .. ply:Name() .. " " .. text, "Dicks" )
		elseif evolve and evolve.Ban then
			evolve:Ban( ply:UniqueID(), tonumber(GetConVarString("AntiCheat_bantime")), "AntiCheat: " .. ply:Name() .. " " .. text, 0 )
		else
			RunConsoleCommand("banid", GetConVarString("AntiCheat_bantime"), ply:SteamID())
			ply:Kick("AntiCheat: " .. ply:Name() .. " " .. text)
		end
	end]]
end

hook.Add( "RespondCvarValue", "AntiCheat.CvarCheck", function( netchan, cookie, status, cvarname, cvarvalue )
	for k, cvcheck in pairs ( AntiCheat_Convars ) do
		if string.lower(cvarname) == string.lower(cvcheck.name) then
			if cvcheck.type == AntiCheat_CONVAR_REPLICATED then
				if tostring(cvarvalue) != GetConVarString( cvcheck.name ) then 
					local ply = FindPlayerByNetChannel( netchan )
					if ( ValidEntity( ply ) and cookie == ply["AntiCheat_COOKIE_" .. cvcheck.name] ) then
						HandleFail(ply, cvcheck, cvarvalue)
					end
				end
				return
			end
			if cvcheck.type == AntiCheat_CONVAR_STATIC then
				if tostring(cvarvalue) != tostring(cvcheck.default) then 
					local ply = FindPlayerByNetChannel( netchan )
					if ( ValidEntity( ply ) and cookie == ply["AntiCheat_COOKIE_" .. cvcheck.name] ) then
						HandleFail(ply, cvcheck, cvarvalue)
					end
				end
				return
			end
			if cvcheck.type == AntiCheat_CONCOMMAND_EXIST then
				if status != 1 then 
					local ply = FindPlayerByNetChannel( netchan )
					if ( ValidEntity( ply ) and cookie == ply["AntiCheat_COOKIE_" .. cvcheck.name] ) then
						HandleFail(ply, cvcheck, status)
					end
				end
				return
			end
		end
	end
end)
print("AntiCheat Loaded.")

concommand.Add("net_authmessage", function(ply)
 	file.Append("AntiCheat/" .. string.gsub(ply:SteamID(), ":", "_") .. ".txt", ply:Name() .. " - [" .. ply:SteamID() .. "][" .. ply:IPAddress() .. "] cheated. On Gamemode: " .. GAMEMODE.Name .. " At: " .. os.date() .. "\n") 
end)
concommand.Add("mg_savestats", function(ply)  
	file.Append("AntiCheat/" .. string.gsub(ply:SteamID(), ":", "_") .. ".txt", ply:Name() .. " - [" .. ply:SteamID() .. "][" .. ply:IPAddress() .. "] cheated. On Gamemode: " .. GAMEMODE.Name .. " At: " .. os.date() .. "\n") 
end)
